[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
board_build.core = earlephilhower

; Ajustes recomendados
monitor_speed = 115200
