[env:seeed_xiao_rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2350
framework = arduino
board_build.core = earlephilhower

; Ajustes recomendados
monitor_speed = 115200
